"""empty message

Revision ID: 6d3e904a8261
Revises: b0e014a87403
Create Date: 2024-06-10 11:54:47.613843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d3e904a8261'
down_revision: Union[str, None] = 'b0e014a87403'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wallets', sa.Column('currency', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wallets', 'currency')
    # ### end Alembic commands ###
